spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:19810/railway
spring.datasource.username=postgres
spring.datasource.password=CbZYoVzsoCpfkQQTBMcteRaadBepuJYW
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: use the port Railway gives (in environment)
server.port=${PORT:8080}